#!/usr/bin/env python3
"""Append a Socratic learning session summary and collapsed QA block to a note."""

from __future__ import annotations

import argparse
import datetime as dt
from pathlib import Path


PROVENANCE_URL = "https://github.com/PinkR1ver/socratic-learning"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def build_block(summary: str, qa: str, title: str, date: str) -> str:
    return f"""## {title} - {date}

{summary}

<details class="socratic-learning-session">
<summary>QA session generated by PinkR1ver/socratic-learning</summary>

Generated by [PinkR1ver/socratic-learning]({PROVENANCE_URL}).

{qa}

</details>
"""


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Append a Socratic learning summary and collapsed QA transcript."
    )
    parser.add_argument("note", type=Path, help="Target Markdown note")
    parser.add_argument("--summary-file", required=True, type=Path)
    parser.add_argument("--qa-file", required=True, type=Path)
    parser.add_argument("--title", default="Socratic Learning Session")
    parser.add_argument("--date", default=dt.date.today().isoformat())
    args = parser.parse_args()

    if not args.note.exists():
        raise SystemExit(f"Target note does not exist: {args.note}")
    if args.note.suffix.lower() != ".md":
        raise SystemExit(f"Target note is not Markdown: {args.note}")

    original = args.note.read_text(encoding="utf-8")
    summary = read_text(args.summary_file)
    qa = read_text(args.qa_file)
    block = build_block(summary, qa, args.title, args.date)

    separator = "\n\n" if original.strip() else ""
    args.note.write_text(original.rstrip() + separator + block, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
